@startuml
skinparam linetype ortho
'https://plantuml.com/class-diagram

class Kurs{
+{static}id: Integer
-titel: String
-kurzbeschreibung: String
-dauer: Integer
-maxTeilnehmer: Integer
-preis: Integer
}

class Kursveranstaltung{
- kurs_id: Integer
}

class Raum{
+{static}id: Integer
-platz: Integer
}

class Gebaeude{
+{static}id: Integer
-adresse: String
}

class Vortragende{
+{static}id: Integer
-name: String
-qualifikation: Kurs[]
}

class Kurseinladung{
-beginn: Date
-end: Date
-adresse: String
-raum_id: Integer
-teilnehmer_id: Integer
-kurs_id: Integer
}

class Teilnehmer{
+{static}id: Integer
-name: String
}

class Bestaetigung{
+{static}id: Integer
-kurs_id: Integer
-teilnehmer_id: Integer
}

class Rechnung{
+{static}id: Integer
-bezahlt: boolean
-kurs_preis: Integer
-teilnehmer_id: Integer
-kurs_id: Integer
}

class Mahnung{
-rechnung_id: Integer
}

class Pruefung{
+{static}id: Integer
-antritt: boolean
-erfolg: String
}


Kurs "*"--"*" Kurs

(Kurs, Kurs) .. Vorraussetzungen

Raum "*"-->"1" Gebaeude

Kurs "*"--"*" Raum

(Kurs, Raum) .. Ort

Kurs "*"--"*" Vortragende

(Kurs, Vortragende) .. Eingeteilt

Kurseinladung "1"-->"1" Anmeldung

Bestaetigung "1"-->"1" Anmeldung

Rechnung "*"-->"1" Teilnehmer

Teilnehmer "*"--"*" Kurs

(Teilnehmer, Kurs) .. Anmeldung

Rechnung "1"<-->"0,1" Mahnung

Pruefung "1"--"*" Kurs

(Pruefung, Kurs) .. Antritt

Vortragende "1"<--"*" Kurs :"hauptverantwortlich"



@enduml


@startuml
skinparam linetype ortho

class Kurs{
id: Integer
thema: String
}

class Kursveranstaltung{
kurs_id: Integer
datum: date
}

class Teilnehmer{
teilnehmer_id: Integer
}

class Raum{
raum_id: Integer
}

class Vortragende{
}

class Gebaeude{
adresse: String
}

class Buchung{
gezahlt: boolean
}

class Mahnung{
}

class Gebiete{

}

Kurs "1"<--"*" Kursveranstaltung
Kursveranstaltung <-- Teilnehmer :besucht
(Kursveranstaltung, Teilnehmer) .. Buchung
Kursveranstaltung "*"--"*" Teilnehmer
(Kursveranstaltung, Teilnehmer) .. besucht
Kursveranstaltung "*"--"1" Raum :findet statt
Raum "*"--"1" Gebaeude :befindet sich
Buchung -- Mahnung
Vortragende "*"--"*" Kursveranstaltung :trägt vor
Vortragende "1"<--"*" Kursveranstaltung :leitet
Vortragende "*"--"*" Gebiete :qualifiziert
Kurs -- Gebiete

@enduml

